linked_words:
  type: list
  default: 'discourse,https://www.discourse.org|meta,https://meta.discourse.org'
abbreviations:
  type: list
  default: 'rtfm,Read The Fine Manual|tl;dr,Too Long; Didn''t Read'
  description:
    en: "List of abbreviations to add `abbr` tags to in posts, as well as their meanings."
    da: "Liste over forkortelser der skal tilføjes `abbr` tags til i indlæg, samt deres betydninger."
replaced_words:
  type: list
  default: 'fack,fork|suck,soak'
excluded_tags:
  type: list
  list_type: compact
  default: 'code|pre'
