linked_words:
  type: list
  default: "discourse,https://www.discourse.org|meta,https://meta.discourse.org"
excluded_tags:
  type: list
  list_type: compact
  default: "code|pre"
excluded_classes:
  type: list
  list_type: compact
  default: "onebox"
regex_substitute_or_character:
  default: "¦"
left_word_boundary:
  type: list
  list_type: compact
  default: "\\s|:|.|;|,|!|?|…|(|[|{"
right_word_boundary:
  type: list
  list_type: compact
  default: "\\s|:|.|;|,|!|?|…|}|]|)"
